version: '3.8'
services:
    java-maven-app:
      image: anas99anas/java-maven-app:jma-1.1
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd




